version: '3'

services:
  angular:
    build:
      context: ./angular-client
      dockerfile: Dockerfile
    ports:
     - "4200:4200"
    volumes:
      - ./angular-client:/app
  express:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
